services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"

  app1:
    image: ccs1201/rinha-backend-2025:latest
    container_name: backend-api1
    hostname: app1
    ports:
      - "9010:9010"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - THREAD_POOL_SIZE=75
      - redis-host=redis
      - JAVA_OPTS=-Dlogging.level.root=warn -Dspring.threads.virtual.enabled=false -XX:+UseSerialGC -Xmx70m -Xms60m -XX:MaxMetaspaceSize=70m -XX:+HeapDumpOnOutOfMemoryError
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "140MB"

  app2:
    image: ccs1201/rinha-backend-2025:latest
    container_name: backend-api2
    hostname: app2
    ports:
      - "9011:9011"
      - "8081:8080"
    environment:
      - SERVER_PORT=8080
      - THREAD_POOL_SIZE=75
      - redis-host=redis
      - JAVA_OPTS=-Dlogging.level.root=warn -Dspring.threads.virtual.enabled=false -XX:+UseSerialGC -Xmx70m -Xms60m -XX:MaxMetaspaceSize=70m -XX:+HeapDumpOnOutOfMemoryError
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "140MB"

  redis:
    image: redis:7-alpine
    container_name: redis
    hostname: redis
    command: redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru --save "" --tcp-keepalive 60 --timeout 0
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true