x-service-templates:
  app: &app
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
    image: ccs1201/rinha-backend-2025:latest
    depends_on:
      - backend-db
    environment:
      - server.port=8080
      - thread_pol_size=15
      - thread_queue_size=20000
      - server.undertow.threads.worker=30
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rinha
      - SPRING_DATASOURCE_USERNAME=rinha
      - SPRING_DATASOURCE_PASSWORD=rinha
      - JAVA_OPTS=-Dlogging.level.root=warn -Dspring.threads.virtual.enabled=false -XX:+UseSerialGC -Xmx70m -Xms70m -XX:MaxMetaspaceSize=45m -XX:TieredStopAtLevel=1 -XX:+TieredCompilation -Djava.security.egd=file:/dev/./urandom
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "100MB"


services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"

  app1:
    <<: *app
    container_name: backend-api1
    hostname: app1
    ports:
      - "8080:8080"

  app2:
    <<: *app
    container_name: backend-api2
    hostname: app2
    ports:
      - "8081:8080"

  backend-db:
    image: postgres:17-alpine
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
    volumes:
      - ./init.sql/init-backend-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "120MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true