services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  app1:
    image: ccs1201/rinha-backend-2025:latest
    hostname: app1
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "150MB"

  app2:
    image: ccs1201/rinha-backend-2025:latest
    hostname: app2
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "150MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true