services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  app1:
    image: ccs1201/rinha-backend-2025:latest
    hostname: app1
    ports:
      - "9010:9010"
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - INSTANCE_NAME=app1
      - SERVER_PORT=8080
      - JAVA_OPTS=-XX:+UseSerialGC -Xmx120m -Xms120m -XX:MaxMetaspaceSize=64m -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=9010 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=0.0.0.0
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "150MB"

  app2:
    image: ccs1201/rinha-backend-2025:latest
    hostname: app2
    ports:
      - "9011:9011"
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - INSTANCE_NAME=app2
      - SERVER_PORT=8080
      - JAVA_OPTS=-XX:+UseSerialGC -Xmx120m -Xms120m -XX:MaxMetaspaceSize=64m -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=9011 -Dcom.sun.management.jmxremote.rmi.port=9011 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=0.0.0.0
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "150MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true