services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"

  app1:
    image: ccs1201/rinha-backend-2025:latest
    container_name: backend-api1
    hostname: app1
    ports:
      - "9010:9010"
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - INSTANCE_NAME=app1
      - SERVER_PORT=8080
      - THREAD_POOL_SIZE=75
      - JAVA_OPTS=-Dlogging.level.root=warn -Dspring.threads.virtual.enabled=false -XX:+UseSerialGC -Xmx140m -Xms140m -XX:MaxMetaspaceSize=40m -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "160MB"

  app2:
    image: ccs1201/rinha-backend-2025:latest
    container_name: backend-api2
    hostname: app2
    ports:
      - "9011:9011"
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - INSTANCE_NAME=app2
      - SERVER_PORT=8080
      - THREAD_POOL_SIZE=75
      - JAVA_OPTS=-Dlogging.level.root=warn -Dspring.threads.virtual.enabled=false -XX:+UseSerialGC -Xmx140m -Xms140m -XX:MaxMetaspaceSize=40m -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=9011 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "160MB"

#  redis:
#    image: redis:7-alpine
#    container_name: redis-storage
#    command: redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru --save ""
#    ports:
#      - "6379:6379"
#    networks:
#      - backend
#    deploy:
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: "60MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true