x-backend-templates:
  app: &app
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: ccs1201/rinha-2025-vertex:latest
    depends_on:
      - backend-db
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "117.50MB"
#          memory: "128MB"

  app-env: &app-env
    client-processor-timeout: "1500"
    datasource-class-name: "org.postgresql.Driver"
    datasource-maximum-pool-size: "5"
    datasource-minimum-idle: "5"
    datasource-password: "rinha"
    datasource-timeout: "2000"
    datasource-url: "jdbc:postgresql://postgres:5432/rinha"
    datasource-username: "rinha"
    payment-processor-default-url: "http://payment-processor-default:8080"
    payment-processor-fallback-url: "http://payment-processor-fallback:8080"
    server-port: "8080"
    server-io-threads: "4"
    server-workers-threads: "50"
    thread-pool-size: "1"
    thread-queue-size: "200"
    warmup: "true"
    warmup_rounds: "5000"
    JAVA_OPTS: "\
    -Xmx95m \
    -Xms95m \
    -XX:MaxMetaspaceSize=35m \
    -XX:+UseG1GC \
    -XX:+UseNUMA \
    -Xss512k \
    -XX:+UseCompressedOops \
    -XX:+AlwaysPreTouch \
    -Xbatch \
    -XX:+ExitOnOutOfMemoryError \
    -XX:+TieredCompilation \
    -XX:TieredStopAtLevel=1 \
    -XX:CompileThreshold=100 "
#    -XX:+UnlockDiagnosticVMOptions \
#    -XX:+PrintCompilation \
#    -XX:+PrintTieredEvents \
#    -XX:+PrintCodeCache \
#    -XX:+PrintInlining"


volumes:
  backend-db: {}

services:
  nginx:
    image: nginx:alpine
    container_name: backend-nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "15MB"

  app1:
    <<: *app
    container_name: backend-api1
    hostname: app1
    environment:
      <<: *app-env
      warmup_instance: "app2"

  app2:
    <<: *app
    container_name: backend-api2
    hostname: app2
    environment:
      <<: *app-env
      warmup_instance: "app1"

  backend-db:
    image: postgres:17-alpine
    container_name: backend-db
    hostname: postgres
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
    volumes:
      - ./db/init-backend-db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/init-config.sh:/docker-entrypoint-initdb.d/init-config.sh
      - backend-db:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
