spring.application.name=ccs1201-rinha-backend-2025
server.port=8080
spring.main.banner-mode=off
spring.jmx.enabled=false
spring.application.admin.enabled=false

# Disable performance-impacting features
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration,org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.web.servlet.HttpEncodingAutoConfiguration

# Disable RequestContextHolder and filters
server.servlet.context-parameters.contextClass=org.springframework.web.context.support.AnnotationConfigWebApplicationContext
spring.mvc.async.request-timeout=-1
spring.mvc.dispatch-options-request=false
spring.mvc.dispatch-trace-request=false
spring.mvc.log-request-details=false
spring.mvc.log-resolved-exception=false

# Undertow
server.undertow.threads.io=2
server.undertow.threads.worker=30
server.undertow.buffer-size=1024
server.undertow.direct-buffers=true
server.undertow.max-http-post-size=1KB
server.undertow.no-request-timeout=5000
server.undertow.options.server.record-request-start-time=false

spring.jackson.serialization.write-dates-as-timestamps=false

#Hikari
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-init-sql=SELECT 1 WHERE 1 = 1;

##########
logging.level.br.com.ccs.rinha=info
payment-processor.default.url=http://payment-processor-default:8080
payment-processor.fallback.url=http://payment-processor-fallback:8080


